name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: false
        cache-read-only: false

    - name: Configure Gradle for network resilience
      run: |
        mkdir -p ~/.gradle
        cat > ~/.gradle/gradle.properties << EOF
        org.gradle.daemon=false
        org.gradle.parallel=true
        org.gradle.caching=true
        org.gradle.configuration-cache=false
        org.gradle.network.retry.initial.delay=2000
        org.gradle.network.retry.max.delay=30000
        org.gradle.network.retry.max.attempts=10
        systemProp.http.keepAlive=false
        systemProp.http.socketTimeout=120000
        systemProp.http.connectionTimeout=120000
        systemProp.http.nonProxyHosts=localhost|127.*|[::1]
        systemProp.http.maxRedirects=10
        systemProp.https.protocols=TLSv1.2,TLSv1.3
        EOF

    - name: Check code formatting (with retry)
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 5
        retry_on: error
        retry_wait_seconds: 30
        command: ./gradlew spotlessCheck --no-daemon --refresh-dependencies --stacktrace

    - name: Build with tests (with retry)
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 25
        max_attempts: 5
        retry_on: error
        retry_wait_seconds: 60
        command: ./gradlew clean build --no-daemon --refresh-dependencies --parallel --stacktrace

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/test-results/

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-reports
        path: |
          **/build/reports/
          **/.gradle/
