name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # fetch full history to ensure any files used by detection or submodules are present
        fetch-depth: 0
        # if you rely on submodules, enable this
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    # Debugging: list repository files so CI logs show whether the expected Gradle/Gradle wrapper files
    # and versions files are present. If you still see the "No file matched" error, check the
    # repository layout or whether the workflow is running in a different repository/fork.
    - name: List repository root files (debug)
      run: |
        echo "PWD: $(pwd)";
        echo "--- root files ---";
        ls -la;
        echo "--- find gradle files ---";
        find . -maxdepth 4 -type f -name "*gradle*" -o -name "gradle-wrapper.properties" -o -name "*.versions.toml" -print || true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check code formatting
      run: ./gradlew spotlessCheck --no-daemon -Dorg.gradle.configuration-cache=false

    - name: Build (Gradle)
      run: ./gradlew clean build --no-daemon -Dorg.gradle.configuration-cache=false

    - name: Run tests
      run: ./gradlew test --no-daemon -Dorg.gradle.configuration-cache=false
